---
- name: Install packages with cache update
  apt:
    name: '{{ packages }}'
    update_cache: yes
    state: present
    force: yes
  vars:
    packages:
      - apt-file
      - apt-mirror
      - aptitude
      - curl
      - docker
      - docker-compose
      - mc
      - ncdu
      - ruby
      - tcpdump
      - tilix
      - tmux
      - tree
      - vim
      - wget

- name: Download Atom and Kraken
  get_url:
    url: '{{ item.url }}'
    dest: '{{ item.deb }}'
    mode: 'a+x'
    validate_certs: false
  with_items:
    - { url: 'https://atom.io/download/deb', deb: '/tmp/atom.deb' }
    - { url: 'https://release.gitkraken.com/linux/gitkraken-amd64.deb', deb: '/tmp/kraken.deb' }

- name: Install Atom and Kraken
  apt:
    deb: '{{ item }}'
  with_items:
    - /tmp/atom.deb
    - /tmp/kraken.deb
